---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reboot system
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for hardening changes."
    pre_reboot_delay: 120
    post_reboot_delay: 30
    reboot_timeout: 600

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
