---
- name: Create a new user with SSH keypair and configure SSH login
  hosts: all
  become: yes
  # vars:
  #   username: "newuser"
  #   ssh_key_comment: "newuser@ansible"
  #   email_recipient: "recipient@example.com"
  tasks:
    - name: Ensure the user is created
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        create_home: yes
        groups: "sshusers"
    
    - name: Create .ssh directory for the user
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'
    
    - name: Generate SSH key pair on target
      ansible.builtin.command:
        cmd: ssh-keygen -t rsa -b 4096 -f /home/{{ username }}/.ssh/id_rsa -N "" -C "{{ ssh_key_comment }}"
      become_user: "{{ username }}"
      register: ssh_keygen_result

    - name: Change ownership of SSH key files
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh/id_rsa"
        state: file
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

    - name: Change ownership of SSH public key file
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh/id_rsa.pub"
        state: file
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'
    
    - name: Ensure password authentication is disabled and key-based login is enabled
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
    
    - name: Ensure PubkeyAuthentication is enabled
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present

    - name: Restart SSH service to apply changes
      ansible.builtin.systemd:
        name: sshd
        state: restarted
        enabled: yes

- name: Output the SSH private key
  hosts: localhost
  tasks:
    - name: Display SSH private key
      ansible.builtin.debug:
        msg: "SSH private key for {{ username }}:\n{{ ssh_key.private_key }}"

- name: Send the SSH private key via email
  hosts: localhost
  vars:
    email_subject: "SSH Private Key for {{ username }}"
    email_body: |
      Hello,

      Please find attached the SSH private key for the user {{ username }}.

      Private Key:
      {{ lookup('file', "/home/{{ username }}/.ssh/id_rsa") }}

      Regards,
      Your Ansible Automation
  tasks:
    - name: Send an email with the private key
      community.general.mail:
        host: smtp-relay.sendinblue.com
        port: 587
        username: "{{ mail_username }}"
        password: "{{ mail_password }}"
        from: "{{ mail_username }}"
        to: "{{ email_recipient }}"
        subject: "{{ email_subject }}"
        body: "{{ email_body }}"