---
- name: Hardening Ubuntu 24.04 Server
  hosts: all
  become: yes
  vars:
    ssh_port: 22
    allowed_ssh_users:
      - localadmin  # Ersetze "your_user" mit deinem SSH-Benutzer
      - ansible
  tasks:
    - name: Ensure system is up-to-date
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - fail2ban
          - nginx
        state: latest

    - name: Configure SSH settings
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        create: yes
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^#?Port', line: "Port {{ ssh_port }}" }
        - { regexp: '^#?PermitRootLogin', line: "PermitRootLogin no" }
        - { regexp: '^#?PasswordAuthentication', line: "PasswordAuthentication no" }
        - { regexp: '^#?ChallengeResponseAuthentication', line: "ChallengeResponseAuthentication no" }
        - { regexp: '^#?X11Forwarding', line: "X11Forwarding no" }
        - { regexp: '^#?UsePAM', line: "UsePAM yes" }
        - { regexp: '^#?MaxAuthTries', line: "MaxAuthTries 3" }
        - { regexp: '^#?AllowUsers', line: "AllowUsers {{ allowed_ssh_users | join(' ') }}" }
      notify:
        - Restart SSH

    - name: Set fail2ban to monitor SSH
      lineinfile:
        path: /etc/fail2ban/jail.local
        state: present
        create: yes
        line: |
          [sshd]
          enabled = true
      notify:
        - Restart Fail2Ban
        
    - name: Configure remote syslog server
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^#*.*'
        line: '*.* @10.10.11.105:514'
        state: present
        backup: yes
      notify: Restart rsyslog

    - name: Reboot system
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for hardening changes."
        pre_reboot_delay: 120
        post_reboot_delay: 30
        reboot_timeout: 600
      
  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted

    - name: Restart Fail2Ban
      service:
        name: fail2ban
        state: restarted

    - name: Restart rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: restarted

    
