---
- name: Update all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Install EPEL repository
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Install common packages
  ansible.builtin.yum:
    name:
      - vim
      - wget
      - curl
    state: present
 